version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cache-increment-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: cache-increment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CacheIncrementDb
      MYSQL_USER: cacheuser
      MYSQL_PASSWORD: cachepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  mysql_data:
