using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Acme.EnumExtensions.Generator;

/// <summary>
/// Gera <c>ToStringFast()</c> para cada enum marcado com <c>[EnumExtensions]</c>.
///
/// O que se ganha: <c>Enum.ToString()</c> usa reflexão e aloca; um <c>switch</c> sobre os
/// membros conhecidos em tempo de compilação devolve uma constante de string.
///
/// O que se aprende: como montar um pipeline incremental que não recalcula o que não
/// mudou. A ordem importa — filtrar cedo, transformar para um modelo pequeno e com
/// igualdade por valor, e só então gerar.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EnumExtensionsGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Acme.EnumExtensions.EnumExtensionsAttribute";

    /// <summary>
    /// O atributo é injetado pelo próprio gerador, via saída de pós-inicialização. Assim o
    /// consumidor não precisa referenciar nenhuma biblioteca em tempo de execução — o
    /// atributo passa a existir na compilação dele.
    /// </summary>
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Acme.EnumExtensions
        {
            /// <summary>
            /// Marca um enum para receber os métodos de extensão gerados.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
            [global::System.Diagnostics.Conditional("ACME_ENUM_EXTENSIONS_KEEP_ATTRIBUTE")]
            internal sealed class EnumExtensionsAttribute : global::System.Attribute
            {
            }
        }
        """;

    /// <summary>
    /// Enum inacessível de fora do tipo que o contém não pode receber extensão pública —
    /// o código gerado fica em outro arquivo e não compilaria.
    /// </summary>
    private static readonly DiagnosticDescriptor InaccessibleEnum = new DiagnosticDescriptor(
        id: "AEE001",
        title: "Enum inacessivel para geracao de extensoes",
        messageFormat: "O enum '{0}' e '{1}' e nao pode receber extensoes geradas; use internal ou public",
        category: "Acme.EnumExtensions",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Etapa 0: o atributo. Roda uma vez, antes de qualquer analise.
        context.RegisterPostInitializationOutput(postInitialization =>
            postInitialization.AddSource("EnumExtensionsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Etapa 1: achar os enums marcados. ForAttributeWithMetadataName e o caminho
        // barato — o compilador mantem um indice de atributos, e o predicado sintatico
        // nem chega a ser chamado para a maioria dos nos.
        IncrementalValuesProvider<Result> enums = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.EnumDeclarationSyntax,
                transform: static (syntaxContext, _) => Transform(syntaxContext));

        // Etapa 2: gerar. Um arquivo por enum — nome de arquivo unico por tipo, senao o
        // compilador reclama de fonte duplicada.
        context.RegisterSourceOutput(enums, static (productionContext, result) =>
        {
            if (result.Diagnostic is not null)
            {
                productionContext.ReportDiagnostic(result.Diagnostic);

                return;
            }

            if (result.Enum is null)
            {
                return;
            }

            productionContext.AddSource(
                $"{result.Enum.Namespace ?? "global"}.{result.Enum.Name}.EnumExtensions.g.cs",
                SourceText.From(Render(result.Enum), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Converte o símbolo do compilador no modelo pequeno do gerador.
    ///
    /// <b>Nada de <c>ISymbol</c> ou <c>SyntaxNode</c> atravessa esta fronteira.</b> Esses
    /// tipos carregam a árvore e o modelo semântico inteiros; guardá-los no pipeline
    /// impede o cache de funcionar e segura memória entre compilações.
    /// </summary>
    private static Result Transform(GeneratorAttributeSyntaxContext syntaxContext)
    {
        if (syntaxContext.TargetSymbol is not INamedTypeSymbol enumSymbol)
        {
            return default;
        }

        if (enumSymbol.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected
            or Accessibility.ProtectedAndInternal)
        {
            return new Result(
                null,
                Diagnostic.Create(
                    InaccessibleEnum,
                    enumSymbol.Locations.FirstOrDefault(),
                    enumSymbol.Name,
                    enumSymbol.DeclaredAccessibility.ToString().ToLowerInvariant()));
        }

        List<string> members = new List<string>();

        foreach (ISymbol member in enumSymbol.GetMembers())
        {
            if (member is IFieldSymbol { ConstantValue: not null } field)
            {
                members.Add(field.Name);
            }
        }

        string? namespaceName = enumSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : enumSymbol.ContainingNamespace.ToDisplayString();

        string accessibility = enumSymbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";

        return new Result(new EnumToGenerate(namespaceName, enumSymbol.Name, accessibility, members), null);
    }

    private static string Render(EnumToGenerate enumToGenerate)
    {
        StringBuilder builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (enumToGenerate.Namespace is not null)
        {
            builder.AppendLine($"namespace {enumToGenerate.Namespace};");
            builder.AppendLine();
        }

        string enumReference = enumToGenerate.Namespace is null
            ? enumToGenerate.Name
            : $"global::{enumToGenerate.Namespace}.{enumToGenerate.Name}";

        builder.AppendLine($"{enumToGenerate.Accessibility} static class {enumToGenerate.Name}Extensions");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Devolve o nome do valor sem reflexao e sem alocar.</summary>");
        builder.AppendLine($"    public static string ToStringFast(this {enumReference} value)");
        builder.AppendLine("        => value switch");
        builder.AppendLine("        {");

        foreach (string member in enumToGenerate.Members)
        {
            builder.AppendLine($"            {enumReference}.{member} => nameof({enumReference}.{member}),");
        }

        builder.AppendLine("            _ => value.ToString(),");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Todos os valores declarados, sem alocar array novo a cada chamada.</summary>");
        builder.AppendLine($"    public static global::System.ReadOnlySpan<{enumReference}> DeclaredValues");
        builder.AppendLine("        => new[]");
        builder.AppendLine("        {");

        foreach (string member in enumToGenerate.Members)
        {
            builder.AppendLine($"            {enumReference}.{member},");
        }

        builder.AppendLine("        };");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Modelo ou diagnóstico. Struct para não alocar, e com igualdade por valor herdada
    /// dos campos.
    /// </summary>
    private readonly struct Result
    {
        public Result(EnumToGenerate? enumToGenerate, Diagnostic? diagnostic)
        {
            Enum = enumToGenerate;
            Diagnostic = diagnostic;
        }

        public EnumToGenerate? Enum { get; }

        public Diagnostic? Diagnostic { get; }
    }
}
